GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Full Stack web developer",
    "author": "Rachit PAtel",
    "url": "http://www.fullstackweb.com",
    "likes": 100
}